/**
 * Story registration for `@storybook/react-native` 7.x.
 *
 * Hand-authored (not generated by `sb-rn-get-stories`). Keeping this explicit
 * lets Metro resolve story modules without `require.context` magic and keeps
 * the catalog reviewable in PRs. Add a `require(...)` line per new
 * `*.stories.tsx` file under `src/lib/design-system/components/`.
 */
import { start } from '@storybook/react-native';

const normalizedStories = [
  {
    titlePrefix: '',
    directory: './src/lib/design-system/components',
    files: '*.stories.@(ts|tsx)',
    importPathMatcher:
      /^\.[\\/](?:src\/lib\/design-system\/components(?:\/(?!\.)(?:(?:(?!(?:^|\/)\.).)*?)\/|\/|$)(?!\.)(?=.)[^/]*?\.stories\.(ts|tsx))$/,
    req: (path: string) => {
      switch (path) {
        case './ProgressDots.stories':
          return require('../src/lib/design-system/components/ProgressDots.stories');
        case './TabToggle.stories':
          return require('../src/lib/design-system/components/TabToggle.stories');
        case './PhoneInput.stories':
          return require('../src/lib/design-system/components/PhoneInput.stories');
        case './OTPInput.stories':
          return require('../src/lib/design-system/components/OTPInput.stories');
        case './ModeCard.stories':
          return require('../src/lib/design-system/components/ModeCard.stories');
        case './RadioCard.stories':
          return require('../src/lib/design-system/components/RadioCard.stories');
        case './Checkbox.stories':
          return require('../src/lib/design-system/components/Checkbox.stories');
        case './Dropdown.stories':
          return require('../src/lib/design-system/components/Dropdown.stories');
        case './VerseCard.stories':
          return require('../src/lib/design-system/components/VerseCard.stories');
        case './Toast.stories':
          return require('../src/lib/design-system/components/Toast.stories');
        default:
          throw new Error(`Unknown story path: ${path}`);
      }
    },
  },
];

(normalizedStories[0].req as unknown as { keys: () => string[] }).keys = () => [
  './ProgressDots.stories',
  './TabToggle.stories',
  './PhoneInput.stories',
  './OTPInput.stories',
  './ModeCard.stories',
  './RadioCard.stories',
  './Checkbox.stories',
  './Dropdown.stories',
  './VerseCard.stories',
  './Toast.stories',
];

declare const global: { STORIES?: typeof normalizedStories; view?: ReturnType<typeof start> };

const view = start({
  annotations: [require('./preview').default],
  storyEntries: normalizedStories,
});

global.STORIES = normalizedStories;
global.view = view;

export { view };
